### PR TITLE
zephyr-dom0-xt: remove dt bins for zephyr domains

### PR DESCRIPTION
**Pull request by GrygiriiS**
The DTB image binaries for simple Zephyr guest domains were addad during development for testing and debug purposes, but it's not needed any more. Hence, drop DTB images from domain cfg for Zephyr based guest domains configuration.

### CODE REVIEW

**Comment by GrygiriiS** [comment]
@lorc @oleksiimoisieiev @dsemenets @firscity

**Comment by oleksiimoisieiev** [comment]
How about dropping .image_dt_path = DISK_BIN_PATH"z_sync.dtb" and blinky as well?

**Comment by oleksiimoisieiev** [comment]
`Reviewed-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>`

**Comment by dsemenets** [comment]
s/addad/added
in commit message

**Review by firscity — APPROVED** [review]
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Pull request merged**
