### PR TITLE
west.yaml: stabilize FATFS revision for release

### PR DESCRIPTION
**Pull request by oleksiimoisieiev**
Set stable revision for the FATFS library that is used int the Release-v0.1.0.

### CODE REVIEW

**Review by lorc — APPROVED** [review]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by dsemenets** [comment]
`Acked-by: Dmytro Semenets <dmytro_semenets@epam.com>`

**Comment by GrygiriiS** [comment]
`Reviewed-by: Grygorii Strashko <grygorii_strashko@epam.com>`

**Comment by oleksiimoisieiev** [comment]
@lorc  @dsemenets @GrygiriiS updated

**Comment by oleksiimoisieiev** [comment]
Closing because of wrong conception.

**Pull request closed without merging**
