### PR TITLE
 zephyr-dom0-xt: add multi fat partition support

### PR DESCRIPTION
**Pull request by GrygiriiS**
This PR add multi fat partition support which can be enabled by  CONFIG_FS_MULTI_PARTITION option.
    
    When this option is enabled the fs mount point should be defined in
    format:
    
        "/0:" - first physical FATFS partition
        "/1:" - second physical FATFS partition
        ...
    
    NOTE: if more then 2 physical FATFS partitions is used the ``PARTITION
    VolToPart[FF_VOLUMES]`` array need to be updated in s``storage.c``.
    
    The physical FATFS partition to be used is selected by
    CONFIG_DOM_STORAGE_FATFS_LOGICAL_DRIVE_NAME Kconfig option which is "/0:"
    by default - the first physical FATFS partition.
    
For example, SD-card with two FATFS partitions. The second FATFS partitions is used to store
guest domain binaries. The Kconfig configuration to be used:

    CONFIG_DOM_STORAGE_FATFS_ENABLE=y
    CONFIG_FS_MULTI_PARTITION=y
    CONFIG_DOM_STORAGE_FATFS_LOGICAL_DRIVE_NAME="1"
    CONFIG_DOM_STORAGE_FATFS_DIR=""

### CODE REVIEW

**Comment by GrygiriiS** [comment]
@oleksiimoisieiev @lorc @firscity @dsemenets

**Review by lorc — APPROVED** [review]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by oleksiimoisieiev** [comment]
LGTM. But this should be merged after https://github.com/xen-troops/meta-xt-prod-devel-rpi5/pull/9

**Comment by GrygiriiS** [comment]
> LGTM. But this should be merged after [xen-troops/meta-xt-prod-devel-rpi5#9](https://github.com/xen-troops/meta-xt-prod-devel-rpi5/pull/9)

Why? It doesn't changes mount point and partition number "0". Specifically done to not depend on incomplete meta.
To change partition use  CONFIG_DOM_STORAGE_FATFS_LOGICAL_DRIVE_NAME="1"

**Pull request merged**
