### PR TITLE
Rpi5 Kconfig update

### PR DESCRIPTION
**Pull request by GrygiriiS**
- fix CONFIG_XRUN_STORAGE_DMA_DEBOUNCE
- increase CONFIG_DOM_MAX to 5

### CODE REVIEW

**Comment by GrygiriiS** [comment]
@oleksiimoisieiev @dsemenets @lorc @firscity

**Comment by oleksiimoisieiev** [comment]
LGTM `Acked-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>`

**Review by lorc — APPROVED** [review]
`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by dsemenets** [comment]
`Acked-by: Dmytro Semenets <dmytro_semenets@epam.com>`

**Pull request merged**
