### PR TITLE
Rpi5: dom0 add xrun lib and fix build

### PR DESCRIPTION
**Pull request by GrygiriiS**
As the xrun is now a separate project, it should be added to the build separately.

PRs
Requires:
https://github.com/xen-troops/zephyr-xenlib/pull/91
https://github.com/xen-troops/zephyr-xrun/pull/1

were merged and broke zephyr-dom0-xt main build.

### CODE REVIEW

**Comment by GrygiriiS** [comment]
@firscity @lorc @oleksiimoisieiev 

It's kinda critical issue.

**Comment by oleksiimoisieiev** [comment]
LGTM `Reviewed-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>`

**Comment by oleksiimoisieiev** [comment]
@firscity please take a look so I can run full build on master

**Comment by oleksiimoisieiev** [comment]
@GrygiriiS How does your project colerates with the following pr https://github.com/xen-troops/zephyr-dom0-xt/pull/22 ?
Maybe one of them should be closed?

**Review by firscity — APPROVED** [review]
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Comment by GrygiriiS** [comment]
> @GrygiriiS How does your project colerates with the following pr #22 ? Maybe one of them should be closed?

The minimum i know the wip_dom0-xt_qemu is used as CI build check  for xenlib.
Regarding consolidation/dropping - this question is not for me it is for corresponding maintainers.

**Comment by firscity** [comment]
@oleksiimoisieiev both branches should be buildable, so nothing should be dropped.

**Pull request merged**
