### PR TITLE
zephyr-dom0-xt: add code coverage support

### PR DESCRIPTION
**Pull request by GrygiriiS**
This patch adds code coverage support which can be enabled by CONFIG_DOM_COVERAGE_ENABLE Kconfig option.

It also adds shell command "gcov dump" to print gcov report to console.

### CODE REVIEW

**Review by lorc — APPROVED** [review]
Great!

`Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>`

**Comment by GrygiriiS** [comment]
Forgot to mention - it depends on https://github.com/xen-troops/zephyr/pull/114

**Review by firscity — APPROVED** [review]
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>`

**Comment by oleksiimoisieiev** [comment]
LGTM `Acked-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>`

**Pull request merged**
