### PR TITLE
zephyr-dom0-xt: rpi5; remove usage of xen_dom0 snippet

### PR DESCRIPTION
**Pull request by GrygiriiS**
The usage of xen_dom0 with Zephyr applications is proved to be
problematic [1]. And moving only "hypervisor" and "memory" nodes in
zephyr-dom0-xt rpi_5.overlay doesn't solve all problems as it cuses build
warning due to different usage of #address-cells/size-cells in RPI5 DTS.

Actulaly if "hypervisor" and "memory" are moved in application board
files the xen_dom0 snippet will be left to provide just proper Xen
HVC console and to enable CONFIG_XEN_DOM0.

Hence, drop usage of xen_dom0 snippet for zephyr-dom0-xt application and
move all needed parts in application board files. Now everything is one
place.

[1] https://github.com/xen-troops/zephyr-xenlib/pulls

### CODE REVIEW

**Comment by GrygiriiS** [comment]
@lorc @oleksiimoisieiev @dsemenets @firscity

**Comment by oleksiimoisieiev** [comment]
Yep. LGTM `Reviewed-by: Oleksii Moisieiev <oleksii_moisieiev@epam.com>`
Closing #107

**Comment by dsemenets** [comment]
Should be appropriate PR in meta-xt-rpi5-prod-devel

**Review by firscity — COMMENTED** [review]
`Acked-by: Dmytro Firsov <dmytro_firsov@epam.com>` with one comment:

What is the purpose of this link in commit description?
`[1] https://github.com/xen-troops/zephyr-xenlib/pulls`

**Comment by dsemenets** [comment]
`Acked-by: Dmytro Semenets <dmytro_semenets@epam.com>`

**Pull request merged**
