### PR TITLE
[WIP] scmi: boot under xen

### PR DESCRIPTION
**Pull request by GrygiriiS**
It can boot to console under xen with scmi:

- arm tf based on https://github.com/xen-troops/arm-trusted-firmware/pull/18
- linux dt overlay updated as below
- xen based on https://github.com/xen-troops/xen/pull/209

```
--- a/arch/arm64/boot/dts/broadcom/bcm2712-rpi-5-scmi.dtso
+++ b/arch/arm64/boot/dts/broadcom/bcm2712-rpi-5-scmi.dtso
@@ -16,6 +16,35 @@ scmi_shm: scmi_shm@0 {
                        compatible = "arm,scmi-shmem";
                        reg = <0 0x1000>;
                };
+              scmi_shm_1: scmi_shm@1 {
+                      compatible = "arm,scmi-shmem";
+                      reg = <0x1000 0x1000>;
+              };
+              scmi_shm_2: scmi_shm@2 {
+                      compatible = "arm,scmi-shmem";
+                      reg = <0x2000 0x1000>;
+              };
+              scmi_shm_3: scmi_shm@3 {
+                      compatible = "arm,scmi-shmem";
+                      reg = <0x3000 0x1000>;
+              };
+              scmi_shm_4: scmi_shm@4 {
+                      compatible = "arm,scmi-shmem";
+                      reg = <0x4000 0x1000>;
+              };
+              scmi_shm_5: scmi_shm@5 {
+                      compatible = "arm,scmi-shmem";
+                      reg = <0x5000 0x1000>;
+              };
+              scmi_shm_6: scmi_shm@6 {
+                      compatible = "arm,scmi-shmem";
+                      reg = <0x6000 0x1000>;
+              };
+              scmi_shm_7: scmi_shm@7 {
+                      compatible = "arm,scmi-shmem";
+                      reg = <0x7000 0x1000>;
+              };
+
        };
 
        firmware {
@@ -26,6 +55,17 @@ scmi {
                        #size-cells = <0>;
                        shmem = <&scmi_shm>;
 
+            epam,secondary-agents = <
+            1 0x82000003 &scmi_shm_1
+            2 0x82000004 &scmi_shm_2
+            3 0x82000005 &scmi_shm_3
+            4 0x82000006 &scmi_shm_4
+            5 0x82000007 &scmi_shm_5
+            6 0x82000008 &scmi_shm_6
+            7 0x82000009 &scmi_shm_7
+            >;
+
+
                        scmi_reset: protocol@16 {
                                reg = <0x16>;
                                #reset-cells = <1>;
```

DomD dom0less linux can't see SCMI. No SCMI in DT.

```

(XEN) *** Serial input to DOM0 (type 'CTRL-a' three times to switch input)
(XEN) Freed 372kB init memory.
(XEN) d1v0 Unhandled SMC/HVC: 0x84000050
(XEN) d1v0 Unhandled SMC/HVC: 0x8600ff01
(XEN) d1v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER4
(XEN) d1v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER8
(XEN) d1v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER12
(XEN) d1v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER16
(XEN) d1v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER20
(XEN) d1v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER24
(XEN) d1v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER28
(XEN) d1v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER32
(XEN) d1v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER36
(XEN) d1v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER0
(XEN) d0v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER4
(XEN) d0v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER8
(XEN) d0v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER12
(XEN) d0v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER16
(XEN) d0v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER20
(XEN) d0v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER24
(XEN) d0v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER28
(XEN) d0v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER32
(XEN) d0v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER36
(XEN) d0v0: vGICD: unhandled word write 0x000000ffffffff to ICACTIVER0
I: scmi base protocol v0002.0000
I: scmi base revision info vendor 'EPAM:' fw version 0x0 protocols:2 agents:8
I: scmi calling method:smc
I: scmi reset rotocol version 0x0001.0000 num_domains:4
(XEN) common/grant_table.c:1909:d0v0 Expanding d0 grant table from 1 to 64 frames
I: sdhc: detected ver:2 vendor_ver:16 supported
I: sdhc: capabilities caps0:15eac832 caps1:8000a577
I: mmc@1000fff000:"reset max bus frequency to 200000000 from 0"


** Booting Zephyr OS build v3.6.0-98-gc5b128bedd0c ***
I: dom0less: attached 1 domains
32muart:~$ (XEN) DOM1: [    0.331872] brcm-pcie 1000120000.pcie: No scmi_reset
I: Card switched to 1.8V signaling
I: storage: block count 124735488, Sector size 512, Memory Size(MB) 60906
I: storage: mounted, binaries folder /1:/dom0/
(XEN) DOM1: 
(XEN) DOM1: Poky (Yocto Project Reference Distro) 5.0.2 raspberrypi5-domd ttyAMA0
(XEN) DOM1: 

uart:~$ 
```

### CODE REVIEW

**Comment by GrygiriiS** [comment]
@oleksiimoisieiev @lorc

**Comment by oleksiimoisieiev** [comment]
Overall looks good, I'm currently building and post tested-by after that

**Comment by lorc** [comment]
Well, it is in WIP state and it makes zephyr pointing to your local branch. I am not sure that it should be merged in this state.

**Comment by GrygiriiS** [comment]
> Well, it is in WIP state and it makes zephyr pointing to your local branch. I am not sure that it should be merged in this state.

Of course it can't, because this (and other meta patches) depends on Xen mediator, but it allows to integrate and test  over all solution on RPI5.

**Comment by GrygiriiS** [comment]
Closing this as it's replaced with https://github.com/xen-troops/zephyr-dom0-xt/pull/37

**Pull request closed without merging**
